### ISSUE TITLE
JGINYUE x99-8D4/2.5G

### ISSUE THREAD

**Issue by jimthedj65** [miyconst/Mi899#136]
I have recently acquired this board and its a bit erratic. I have a 750w power supply with dual 2699v4 TDP 145w and a Intel Arc 380 with 75w. 8 x 32GB ECC samsung ram at 4.6 watts max per chip with a total of about 550 watts with hard disks and SSD/NVME drives. so well within the PSU spec.
[https://www.jginyue.com/index/Article/show/cat_id/48/id/74](url)

It has the standard AMI 5.11 BIOS and looking at Jginyue site my bios is more up to date which makes me think that it might support a different bios as they have a 1.2 version of this board

[https://www.jginyue.com/index/Article/show/cat_id/48/id/79]

I haven't connected it to the internet and it boots sometimes and sometimes it just hangs, I would appreciate any advice on whether this board is just faulty or if an ME update will solve the issues?

happy to provide a sample of this board, I am based in the Philippines.

I will give your software a go, my only other option is to connect to the internet or RMA

**Comment by jimthedj65** [comment]
Further update and left my system off overnight and it sprung to life and booted from the nvme drive and I was able to boot into my [strlec windows  10](https://sergeistrelec.name/winpe-10-8-sergei-strelec-english/) from my USB Ventoy stick and run some tools.

Looking further it appears to be a possible thermal problem or a warm boot after a cold boot. Joined the discord group so will chat there when I am accepted.

**Comment by miyconst** [comment]
I have not tested this motherboard but my experience with Jginyue boards is mostly negative. Your motherboard might have hardware issues, it also might be equipped with a horrible BIOS.

At the moment I do not have any extra info about this particular motherboard and the issue is not related to the Mi899 app itself. The issue is closed but you are welcome to join my Discord and ask there, maybe someone else has some experience with this board.

https://discord.gg/A9UB7rSy
