### ISSUE TITLE
Problem with the last version 1.2.1

### ISSUE THREAD

**Issue by chuckyto** [miyconst/Mi899#36]
If I try to download PEI versions for my TF motherboard, a window comes up showing the file could not be located.
![image](https://user-images.githubusercontent.com/66599759/112308709-bbe6fc80-8ca2-11eb-91f5-17dfdd64e530.png)

**Comment by chuckyto** [comment]
In fact, I just found there is no BIOSES folder included in the zip :)

**Comment by miyconst** [comment]
@chuckyto thank you for reporting the issue, it has already been fixed, but not yet deployed.

The BIOS folder is no longer included with the distributed archive, because it's too large, instead the BIOS files are downloaded form GitHub. You can still get the desired BIOS file by attempting to flash it, Mi899 will download it from the Internet and locate into a temp folder for you.

**Comment by chuckyto** [comment]
Great! Thank you.
It is better this way, Mi899 was getting huge, hehehe

**Comment by miyconst** [comment]
Fixed in [`1.2.2`](https://github.com/miyconst/Mi899/releases/tag/1.2.2).
