### ISSUE TITLE
[Question] Huananzhi X99 F8 Error Code 67 or b7

### ISSUE THREAD

**Issue by robante15** [miyconst/Mi899#41]
A few days ago I flashed the BIOS "Stock Huananzhi X99-F8, Myconst optimized" on my motherboard and for a couple of days it worked fine, yesterday it started to green screen me for milliseconds and it kept working.

Now while I was using it it froze, and when restarting it it no longer worked, the error code it shows is 67 or b7, I already tried to clean the CMOS, disconnect all the peripherals, remove all the RAM and try only one, I tried different RAM, and nothing.

Any suggestions on the problem or on how I could solve it?
Thank you in advance for your contributions @

**Comment by miyconst** [comment]
The `Stock Huananzhi X99-F8, Myconst optimized` BIOS is exactly the same as the original BIOS, I have only modified some fan, RAM, and CPU settings.

Something has happened to the motherboard, and it's not related to Mi899.

To be able to identify which component is the culprit, you have to swap them one by one and test, I could offer some help if you can deliver the motherboard to me.

---------
Closing the issue, since it is not related to Mi899, feel free to text me on Instagram if you need further help - [mi8.se](https://www.instagram.com/mi8.se/).
