### ISSUE TITLE
kllisre x99 v201 compatible bios

### ISSUE THREAD

**Issue by WagnerBezerra2021** [miyconst/Mi899#43]
All right, my friend. I would like to know which bios is compatible with the motherboard kllisre x99 v201. Because in the MI899 program there are no bios when I click on her image. Thank you for the excellent work.

**Comment by miyconst** [comment]
My review for Kllisre X99 V201 is available here - [🇬🇧 Jginyue X99M-Plus D4, Qiyida X99-H9, Kllisre X99 V201, Machinist X99-RS9 – tests and conclusion](https://youtu.be/q7lRrVK6O7E). In short, the motherboard is compatible with Huananzhi X99-8M-F BIOS.

**Comment by elvis-brandao** [comment]
Hello friend, could you let me know where I can find the .bin file for the bios of this [board](https://pt.aliexpress.com/item/4000974911783.html?spm=a2g0s.9042311.0.0.2742b90axNPXbK)? or some other compatible?
it has the x99 chipset itself, I looked at your comment below and the X99-8M-F is only downloadable for B85 and H81 chipsets.
I would be very grateful if you would help me, as I need to re-record the bios using an EPROM recorder and from what I have seen I will need to use a .bin file instead of a .rom

**Comment by miyconst** [comment]
@elvis-brandao here you will find answers for your questions:

[🇬🇧 Kllisre X99 (ZX_99EV3), where to get .bin or .rom BIOS? | Miyconst Answers 00](https://youtu.be/QwJil2AsJnU).
