### ISSUE TITLE
Chipset c226

### ISSUE THREAD

**Issue by sidaonarua** [miyconst/Mi899#46]
Hello friend!

I recently purchased a Machinist X99 RS9 motherboard with the C226 chipset.
Is it possible to perform Unlock Turbo Boost on this chipset?
Could you please add support for this chipset in your application?
Thanks in advance.

**Comment by miyconst** [comment]
Hi @sidaonarua.

I have not had any motherboard with C226 chipset yet, but as far as I know it's compatible with the BIOS options for the B85/H81 chipsets.

If I get a C226 motherboard on my hands, I will verify it myself and update Mi899, for now though, you can use the existing BIOS options, but as always, you are the only one responsible for all possible consequences.

**Comment by Mariolabrador10** [comment]
Hello @sidaonarua. I just got the same motherboard as you with the chipset c226. Have you been able to unlock turbo boost? I don't want to take the risk if nobody with this chipset has tried before. Which bios did you use? By the way, are you able to set your graphic interface to pcie 2.0, because I have 1.0 and I don't know how to change it.

Thanks for your help. It's great to find somebody with the same problem as me :)

**Comment by Mariolabrador10** [comment]
Hello @sidaonarua. I just got the same motherboard as you with the chipset c226. Have you been able to unlock turbo boost? I don't want to take the risk if nobody with this chipset has tried before. Which bios did you use? By the way, are you able to set your graphic interface to pcie 2.0, because I have 1.0 and I don't know how to change it.

Thanks for your help. It's great to find somebody with the same problem as me :)
