### ISSUE TITLE
Machinist x99 RS9 with c226 chipset issue

### ISSUE THREAD

**Issue by Mariolabrador10** [miyconst/Mi899#48]
Hello. I just got the Machinist x99-rs9 motherboard with the chipset c226. Has anyone been able to unlock turbo boost? Which bios have you used? I read that it is compatible with b85 bios but I don't want to take the risk if nobody with this chipset has tried before.
Thanks for your help.

**Comment by miyconst** [comment]
I have not had a chance to test a C226 motherboard, but others report that it works. If you would like to get more or faster feedback I invite you to join my Discord, the link can be found in my [YouTube channel's header](https://www.youtube.com/c/Miyconst).

I am closing the issue, since this is a general question, which is not related to Mi899 app.
