### ISSUE TITLE
kllisre zx-du99d4 v1.12 under linux/ubuntu

### ISSUE THREAD

**Issue by Darkhelion** [miyconst/Mi899#66]
Hello.
I buy a kllisre zx-du99d4 v1.12 with two xeon e5-2696 v3.

I have tested your procedure to flash the bios with the ffs drivers (v3x2_payne_0_0_.efi) and it's don't work (system don't boot) or i have missed something?

But it is possible to use the EFI drivers on ubuntu/linux? I have see the procedure for Windows, but i use this machine for Gaming Ubuntu server and i don't want to use windows.

If necessary , i have the original bios

Thank's by advance

**Comment by miyconst** [comment]
Hi there.

First, I strongly recommend avoid all ZX- boards at all cost. This factory produces low quality products and does not bother to improve anything.

I had several contacts with their representatives, and every time their attitude is very ignorant and discouraging. Basically, they are aware about the quality issues, but don't want to do anything because people keep buying their products.

Regarding your issue, I can only suggest to try to use S3TurboTool instead of the EFI driver, since the custom EFI driver procedure works with Windows only.
