### ISSUE TITLE
BIOS for Kllisre X99-Turbo V1.31 

### ISSUE THREAD

**Issue by xSodium** [miyconst/Mi899#79]
Hi, I'm new here, thanks for your amazing work! I would like to know which bios is compatible with the motherboard Kllisre X99-Turbo V1.31. I can't find it anywhere. It would be a massive help!
And I would like to ask if is it possible to enable Secure Boot in this motherboard with any BIOS update.
Thank you!

**Comment by miyconst** [comment]
I do not recommend and do not support this and similar motherboards, the reason is explained in this video: [🇬🇧 ZX_99EV3, ZX_MINX9D4, ZX_DU99D4, ZX_99D3A4 – please do not buy these motherboards](https://youtu.be/7Pyef_ySHwo). I don't know what BIOS is compatible with your revision, but this page may help you: https://xeon-e5450.ru/socket-2011-3/plexhd-x99/
